<div id="chat_wdw">
    <div id="cabecera_chat">
        <p>Preguntanos lo que necesites!</p>
    </div>
    <div id="cuerpo_chat" style="display: none">

    </div>
    <div id="enviar_chat" style="display: none">
        <div class="row">
            <div class="col-8">
                <input type="text" class="form-control" id="texto_msg">
            </div>
            <div class="col-4">
                <input type="button" value="Enviar" class="btn btn-primary" name="chat_enviar">
            </div>
        </div>
    </div>
</div>
<script src="/socket.io/socket.io.js"></script>
<script>
    document.getElementById('cabecera_chat').onclick = minMax;
    document.body.onload = cargarMsg;
    document.getElementsByName('chat_enviar')[0].onclick = enviarMsg;

    let socket = io();
    socket.on('message', addMessages);

    function minMax() {
        if(document.getElementById('cuerpo_chat').style.display === "none") {
            document.getElementById('cuerpo_chat').style.display = "block";
            document.getElementById('enviar_chat').style.display = "block";
        } else {
            document.getElementById('cuerpo_chat').style.display = "none";
            document.getElementById('enviar_chat').style.display = "none";
        }
    }

    function cargarMsg() {
        let httpRequest = obtainXMLHttpRequest();
        httpRequest.open('POST', 'gest_chat.php', true);
        httpRequest.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
        httpRequest.onreadystatechange = function() {
            if(httpRequest.readyState === 4) {
                if(httpRequest.status === 200) {
                    document.getElementById('cuerpo_chat').innerHTML = httpRequest.responseText;
                    actualizarScroll();
                }
            }
        }
        httpRequest.send('user=<?= $usuario->getEmail() ?>');
    }

    function enviarMsg() {
        let httpRequest = obtainXMLHttpRequest();
        httpRequest.open('POST', 'gest_chat.php', true);
        httpRequest.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
        httpRequest.onreadystatechange = function() {
            if(httpRequest.readyState === 4) {
                if(httpRequest.status === 200) {
                    document.getElementById('texto_msg').value="";
                    document.getElementById('cuerpo_chat').getElementsByTagName('table')[0].innerHTML += httpRequest.responseText;
                    //cargarMsg();
                }
            }
        }
        let data = new Datos(document.getElementById('texto_msg').value, '<?= $usuario->getEmail() ?>');
        let datos = JSON.stringify(data);
        httpRequest.send('new_msg='+datos);
    }

    /*function sendMessage(message){
        $.post('http://localhost:3000/messages', message);
    }*/

    function actualizarScroll() {
        //document.getElementById('cuerpo_chat').scrollTop = document.getElementById('cuerpo_chat').scrollHeight /*- document.getElementById('cuerpo_chat').clientHeight*/;
        document.getElementById('cuerpo_chat').scrollTop = document.getElementById('cuerpo_chat').scrollHeight;
    }

    function Datos(mensaje, usuario) {
        this.mensaje = mensaje;
        this.usuario = usuario;
    }
</script>