<div id="chat_wdw">
    <?php if (!empty($mensajes_nl)): ?>
        <div id="new_msg_user"><?= count($mensajes_nl) ?></div>
    <?php endif; ?>
    <div id="cabecera_chat">
        <p><?= $i_chat_texto1 ?></p>
    </div>
    <div id="cuerpo_chat" style="display: none">

    </div>
    <div id="enviar_chat" style="display: none">
        <div class="row">
            <div class="col-8">
                <input type="text" class="form-control" id="texto_msg">
            </div>
            <div class="col-4">
                <input type="button" value="<?= $i_chat_boton1 ?>" class="btn btn-primary" name="chat_enviar" disabled>
            </div>
        </div>
    </div>
</div>
<!--<script src="/socket.io/socket.io.js"></script>-->
<script>
    $('#cabecera_chat').click(minMax);
    $('[name=chat_enviar]').eq(0).click(enviarMsg);
    $('#texto_msg').keyup(comprobarText);

    function minMax() {
        if (document.getElementById('cuerpo_chat').style.display === "none") {
            $('#cuerpo_chat').fadeIn(300, function () {
                $(this).css('display', 'block');
            });
            $('#enviar_chat').fadeIn(300, function () {
                $(this).css('display', 'block');
            });
            if (!document.getElementsByClassName('msg_user')[0]) {
                cargarMsg();
            }
        } else {
            $('#cuerpo_chat').css('display', 'none');
            $('#enviar_chat').css('display', 'none');
        }
    }

    function cargarMsg() {
        if (document.getElementById('new_msg_user')) {
            document.getElementById('new_msg_user').parentNode.removeChild(document.getElementById('new_msg_user'));
        }
        let httpRequest = obtainXMLHttpRequest();
        httpRequest.open('POST', 'gest_chat.php', true);
        httpRequest.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
        httpRequest.onreadystatechange = function () {
            if (httpRequest.readyState === 1) {
                cargando();
            }
            if (httpRequest.readyState === 4) {
                if (httpRequest.status === 200) {
                    quitarCargando();
                    $('#cuerpo_chat').append(httpRequest.responseText);
                    actualizarScroll();
                }
            }
        };
        httpRequest.send('user=<?= $usuario->getEmail() ?>');
    }

    function comprobarText(event) {
        if (event.target.value !== "") {
            $('[name=chat_enviar]').eq(0).prop("disabled", false);
        } else {
            $('[name=chat_enviar]').eq(0).prop("disabled", true);
        }
    }

    function enviarMsg() {
        let httpRequest = obtainXMLHttpRequest();
        httpRequest.open('POST', 'gest_chat.php', true);
        httpRequest.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
        httpRequest.onreadystatechange = function () {
            if (httpRequest.readyState === 1) {
                cargando();
            }
            if (httpRequest.readyState === 4) {
                if (httpRequest.status === 200) {
                    quitarCargando();
                    //document.getElementById('texto_msg').value="";
                    $('#texto_msg').val("");
                    $('#cuerpo_chat table').append(httpRequest.responseText);
                    //document.getElementById('cuerpo_chat').getElementsByTagName('table')[0].innerHTML += httpRequest.responseText;
                    //cargarMsg();
                    actualizarScroll();
                }
            }
        };
        let data = new Datos($('#texto_msg').val(), '<?= $usuario->getEmail() ?>');
        let datos = JSON.stringify(data);
        httpRequest.send('new_msg=' + datos);
    }

    function actualizarScroll() {
        document.getElementById('cuerpo_chat').scrollTop = document.getElementById('cuerpo_chat').scrollHeight;
    }

    function Datos(mensaje, usuario) {
        this.mensaje = mensaje;
        this.usuario = usuario;
    }

</script>