<div class="container mt-4 formulario_registro">
    <ul class="nav nav-tabs nav-fill" id="myTab2" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="dispositivos_tab" data-toggle="tab" href="#dispositivos" role="tab" aria-controls="dispositivos" aria-selected="true">Dispositivos</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="escenas_tab" data-toggle="tab" href="#escenas" role="tab" aria-controls="escenas" aria-selected="false">Escenas</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="camaras_tab" data-toggle="tab" href="#camaras" role="tab" aria-controls="camaras" aria-selected="false">Cámaras</a>
        </li>
    </ul>
    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="dispositivos" role="tabpanel" aria-labelledby="dispositivos_tab">
            <div class="container w-75 mt-4">
                <div class="row mt-5" id="div_datos">
                    <div class="col-6 mt-3">
                        <?php foreach ($habitaciones as $habitacion) :?>
                        <p class="habitacion_list"><?= $habitacion['habitacion'] ?></p>
                        <?php foreach($dispositivos as $dispositivo) {
                            if($dispositivo['habitacion']==$habitacion['habitacion']):?>
                        <p class="dispositivos_list"><?= $dispositivo['nombre'] ?></p>
                        <input type="hidden" value="<?= $dispositivo['id'] ?>">
                        <?php endif;
                            } endforeach; ?>
                    </div>
                </div>
            </div>
        </div>

        <div class="tab-pane fade" id="escenas" role="tabpanel" aria-labelledby="escenas_tab">
            <?php if(!empty($escenas)) : ?>
            <div class="row">
                <div class="col-6">
                    <?php foreach ($escenas as $escena) : ?>
                    <p><?= $escena['nombre'] ?></p>
                    <?php endforeach; ?>
                </div>
            </div>
            <?php else: ?>
            <div align="center" class="mt-5">
                <h2 class="mt-3">No tienes ninguna escena creada!</h2>
                <h3 class="mt-3">Crea tu primera escena aqui</h3>
                <button type="button" class="btn btn-primary mt-3 mb-3" id="new_scene">Nueva escena</button>
            </div>
            <?php endif;?>
        </div>

        <div class="tab-pane fade" id="camaras" role="tabpanel" aria-labelledby="camaras_tab">
            <?php if(!empty($camaras)) : ?>
            <div class="row">
                <?php foreach($camaras as $camara) :?>
                <div class="offset-1 col-10">
                    <p>Aqui van las camaras</p>
                </div>
                <?php endforeach; ?>
            </div>
            <?php else: ?>
            <div align="center" class="mt-5">
                <h2 class="mt-3">No tienes ninguna cámara configurada!</h2>
                <h3 class="mt-3">Contacta con nosotros para ampliar tu plan</h3>
                <a href="contacto.php" class="btn btn-primary mt-3 mb-3">Contacta con nosotros</a>
            </div>
            <?php endif; ?>
        </div>
    </div>
</div>
<script>
    document.getElementById('new_scene').onclick = nuevaEscena;
    for(let i=0; i<document.getElementsByClassName('dispositivos_list').length; i++) {
        document.getElementsByClassName('dispositivos_list')[i].onclick = seleccionarDisp;
    }
    let dispositivo = "";

    function seleccionarDisp(event) {
        dispositivo = event.target.nextElementSibling.value;
        seleccionar(dispositivo);
        for(let i=0; i<document.getElementsByClassName('dispositivos_list').length; i++) {
            if(event.target===document.getElementsByClassName('dispositivos_list')[i]) {
                event.target.classList.add("disp_act");
            } else {
                if(document.getElementsByClassName('dispositivos_list')[i].classList.contains("disp_act")) {
                    document.getElementsByClassName('dispositivos_list')[i].classList.remove("disp_act");
                }
            }
        }
    }

    function seleccionar(dispositivo) {
        let httpRequest = obtainXMLHttpRequest();
        httpRequest.open('POST', 'datos_dispositivos.php', true);
        httpRequest.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
        httpRequest.onreadystatechange = function() {
            if(httpRequest.readyState === 4) {
                if(httpRequest.status === 200) {
                    if(document.getElementById('datos_disp')!=null) {
                        document.getElementById('datos_disp').parentNode.removeChild(document.getElementById('datos_disp'));
                    }
                    document.getElementById('div_datos').innerHTML += httpRequest.responseText;
                    for(let i=0; i<document.getElementsByClassName('dispositivos_list').length; i++) {
                        document.getElementsByClassName('dispositivos_list')[i].onclick = seleccionarDisp;
                    }
                    document.getElementById('controlador').onclick = cambiarEstado;
                    document.getElementsByName('prg_enviar')[0].onclick = programarDisp;
                }
            }
        }
        httpRequest.send('disp='+dispositivo);
    }

    function cambiarEstado(event) {
        let httpRequest = obtainXMLHttpRequest();
        httpRequest.open('POST', 'actualizar_dispositivo.php', true);
        httpRequest.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
        httpRequest.onreadystatechange = function() {
            if(httpRequest.readyState === 4) {
                if(httpRequest.status === 200) {
                    if(httpRequest.responseText === "bien") {
                        if(event.target.src === "http://localhost/proyecto/imgs/off.png") {
                            event.target.src = "http://localhost/proyecto/imgs/on.png";
                        } else {
                            event.target.src = "http://localhost/proyecto/imgs/off.png";
                        }
                    }
                }
            }
        }
        httpRequest.send('activar='+dispositivo);
    }

    function programarDisp() {
        let programa;
        let httpRequest = obtainXMLHttpRequest();
        httpRequest.open('POST', 'actualizar_dispositivo.php', true);
        httpRequest.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
        httpRequest.onreadystatechange = function() {
            if(httpRequest.readyState === 4) {
                if(httpRequest.status === 200) {
                    if(httpRequest.responseText === "bien") {
                        seleccionar(dispositivo);
                    }

                }
            }
        }
        if(!document.getElementsByName('prg_temp')[0]) {
            programa = new Program(dispositivo, document.getElementsByName('prg_date_start')[0].value, document.getElementsByName('prg_hour_start')[0].value, document.getElementsByName('prg_date_end')[0].value, document.getElementsByName('prg_hour_end')[0].value, null);
        } else {
            programa = new Program(dispositivo, document.getElementsByName('prg_date_start')[0].value, document.getElementsByName('prg_hour_start')[0].value, document.getElementsByName('prg_date_end')[0].value, document.getElementsByName('prg_hour_end')[0].value, document.getElementsByName('prg_temp')[0].value);
        }
        let datos = JSON.stringify(programa);
        alert(datos);
        httpRequest.send('programar='+datos);
    }

    function Program(id_disp, dia_ini, hora_ini, dia_fin, hora_fin, temp) {
        this.id_disp = id_disp;
        this.dia_ini = dia_ini;
        this.hora_ini = hora_ini;
        this.dia_fin = dia_fin;
        this.hora_fin = hora_fin;
        this.temp =  temp;
    }

    function nuevaEscena() {
        alert("Tengo sueño");
    }
</script>