<div class="container mt-5">
    <form method="post" action="form-to-mail.php" id="form_contacto">
        <div class="row">
            <div class="col-12 col-md-6 col-lg-4 offset-lg-2">
                <label><?= $i_contacto_texto1 ?></label>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1"><i class="fas fa-user"></i></span>
                    </div>
                    <input type="text" class="form-control" name="nombre_contacto">
                    <div class="invalid-feedback"><?= $i_guser_error2 ?></div>
                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-4">
                <label><?= $i_contacto_texto2 ?></label>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1"><i class="fas fa-at"></i></span>
                    </div>
                    <input type="text" class="form-control" name="email_contacto">
                    <div class="invalid-feedback"><?= $i_guser_error2 ?></div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-md-6 col-lg-4 offset-lg-2">
                <label><?= $i_contacto_texto3 ?></label>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <label class="input-group-text" for="inputGroupSelect01"><i class="fas fa-question"></i></label>
                    </div>
                    <select class="form-control" name="opciones_contacto">
                        <option value="<?= $i_contacto_option1 ?>"><?= $i_contacto_option1 ?></option>
                        <option value="<?= $i_contacto_option2 ?>"><?= $i_contacto_option2 ?></option>
                        <option value="<?= $i_contacto_option3 ?>"><?= $i_contacto_option3 ?></option>
                        <option value="<?= $i_contacto_option4 ?>"><?= $i_contacto_option4 ?></option>
                        <option value="<?= $i_contacto_option5 ?>"><?= $i_contacto_option5 ?></option>
                        <option value="otra"><?= $i_contacto_option6 ?></option>
                    </select>
                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-4">
                <label><?= $i_contacto_texto4 ?></label>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1"><i class="fab fa-slack-hash"></i></span>
                    </div>
                    <input type="text" class="form-control" name="opcion_contacto" disabled>
                    <div class="invalid-feedback"><?= $i_guser_error2 ?></div>
                </div>
            </div>
        </div>
        <div class="row mt-0">
            <div class="col-12 col-lg-8 offset-lg-2">
                <label><?= $i_contacto_texto5 ?></label>
                <textarea class="form-control" rows="5" name="mensaje_contacto"></textarea>
                <div class="invalid-feedback"><?= $i_guser_error2 ?></div>
                <small class="form-text text-muted"><?= $i_contacto_texto6 ?></small>
                <button type="button" name="submit_contacto"
                        class="btn btn-primary mt-3 hvr-icon-wobble-horizontal"><?= $i_contacto_boton1 ?> <i
                            class="fas fa-envelope hvr-icon ml-1"></i></button>
            </div>
        </div>
    </form>
</div>
<script src="js/login.js"></script>
<script>
    document.getElementsByTagName('select')[0].onchange = habilitarInput;
    document.getElementsByName('submit_contacto')[0].onclick = comprobarFormContacto;
    let regex_email = /^.+@.+\..+/;

    function habilitarInput(event) {
        if (event.target.value === "otra") {
            $('[name="opcion_contacto"]').eq(0).prop("disabled", false);
            document.getElementsByName('opcion_contacto')[0].disabled = false;
        } else {
            document.getElementsByName('opcion_contacto')[0].disabled = true;
        }
    }

    function comprobarFormContacto(event) {
        document.getElementsByName('nombre_contacto')[0].classList.remove('is-invalid');
        document.getElementsByName('email_contacto')[0].classList.remove('is-invalid');
        document.getElementsByName('mensaje_contacto')[0].classList.remove('is-invalid');
        document.getElementsByName('opcion_contacto')[0].classList.remove('is-invalid');
        if (document.getElementById('texto_error')) {
            document.getElementById('texto_error').parentNode.removeChild(document.getElementById('texto_error'));
        }
        if (document.getElementsByName('nombre_contacto')[0].value === "" || document.getElementsByName('email_contacto')[0].value === "" || regex_email.test(document.getElementsByName('email_contacto')[0].value) === false || document.getElementsByName('mensaje_contacto')[0].value === "") {
            if (document.getElementsByName('nombre_contacto')[0].value === "") {
                document.getElementsByName('nombre_contacto')[0].classList.add('is-invalid');
            }
            if (document.getElementsByName('email_contacto')[0].value === "" || regex_email.test(document.getElementsByName('email_contacto')[0].value) === false) {
                document.getElementsByName('email_contacto')[0].classList.add('is-invalid');
            }
            if (document.getElementsByName('mensaje_contacto')[0].value === "") {
                document.getElementsByName('mensaje_contacto')[0].classList.add('is-invalid');
            }
            if (document.getElementsByName('opcion_contacto')[0].value === "" && document.getElementsByName('opcion_contacto')[0].disabled === false) {
                document.getElementsByName('opcion_contacto')[0].classList.add('is-invalid');
            }
        } else
            document.getElementById('form_contacto').submit();
    }

</script>
