<div class="container mt-5">
    <form method="post" action="link.php">
        <div class="row">
            <div class="col-4 offset-2">
                <p><?= $i_contacto_texto1 ?></p>
            </div>
            <div class="col-4">
                <p><?= $i_contacto_texto2 ?></p>
            </div>
        </div>
        <div class="row">
            <div class="col-4 offset-2">
                <input type="text" class="form-control" name="nombre_contacto">
            </div>
            <div class="col-4">
                <input type="text" class="form-control" name="email_contacto">
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-4 offset-2">
                <p><?= $i_contacto_texto3 ?></p>
            </div>
            <div class="col-4">
                <p><?= $i_contacto_texto4 ?></p>
            </div>
        </div>
        <div class="row">
            <div class="col-4 offset-2">
                <select class="form-control">
                    <option value="opcion1"><?= $i_contacto_option1 ?></option>
                    <option value="opcion2"><?= $i_contacto_option2 ?></option>
                    <option value="opcion3"><?= $i_contacto_option3 ?></option>
                    <option value="opcion4"><?= $i_contacto_option4 ?></option>
                    <option value="opcion5"><?= $i_contacto_option5 ?></option>
                    <option value="opcion6"><?= $i_contacto_option6 ?></option>
                </select>
            </div>
            <div class="col-4">
                <input type="text" class="form-control" name="opcion_contacto" disabled>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-4 offset-2">
                <p><?= $i_contacto_texto5 ?></p>
            </div>
        </div>
        <div class="row mt-0">
            <div class="col-8 offset-2">
                <textarea class="form-control" rows="5"></textarea>
            </div>
        </div>
        <small class="form-text text-muted offset-2"><?= $i_contacto_texto6 ?></small>
        <input type="submit" name="submit" class="btn btn-primary mt-3 offset-2" value="<?= $i_contacto_boton1 ?>">
    </form>
</div>
<script src="js/login.js"></script>
<script>
    document.getElementsByTagName('select')[0].onchange = habilitarInput;

    function habilitarInput(event) {
        if(event.target.value === "opcion6") {
            $('[name="opcion_contacto"]').eq(0).prop("disabled", false);
            document.getElementsByName('opcion_contacto')[0].disabled = false;
        } else {
            document.getElementsByName('opcion_contacto')[0].disabled = true;
        }
    }
</script>
