<div class="container mt-4 formulario_registro">
    <ul class="nav nav-tabs nav-fill" id="myTab2" role="tablist">
        <li class="nav-item">
            <a class="nav-link" id="dispositivos_tab" data-toggle="tab" href="#dispositivos" role="tab" aria-controls="dispositivos" aria-selected="true"><?= $i_control_tab1 ?></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="escenas_tab" data-toggle="tab" href="#escenas" role="tab" aria-controls="escenas" aria-selected="false"><?= $i_control_tab2 ?></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="camaras_tab" data-toggle="tab" href="#camaras" role="tab" aria-controls="camaras" aria-selected="false"><?= $i_control_tab3 ?></a>
        </li>
    </ul>
    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade" id="dispositivos" role="tabpanel" aria-labelledby="dispositivos_tab">
            <div class="container w-75 mt-4">
                <div class="row mt-5" id="div_datos">
                    <div class="col-12 col-md-6 mt-3">
                        <?php foreach ($habitaciones as $habitacion) :?>
                        <p class="habitacion_list"><?= $habitacion['habitacion'] ?></p>
                        <?php foreach($dispositivos as $dispositivo) {
                            if($dispositivo['habitacion']==$habitacion['habitacion']):?>
                        <p class="dispositivos_list"><?= $dispositivo['nombre'] ?></p>
                        <input type="hidden" value="<?= $dispositivo['id'] ?>">
                        <?php endif;
                            } endforeach; ?>
                    </div>
                </div>
            </div>
        </div>

        <div class="tab-pane fade" id="escenas" role="tabpanel" aria-labelledby="escenas_tab">
            <div class="container w-75 mt-4">

            <?php if(!empty($escenas)) : ?>
                <div class="row mt-5" id="div_scns">
                    <div class="col-12 col-md-6 mt-3">
                        <p class="scene_title">Escenas</p>
                        <?php foreach($escenas as $escena) :?>
                        <p class="scenes_list"><?= $escena['nombre'] ?></p>
                        <input type="hidden" value="<?= $escena['id'] ?>">
                        <?php endforeach; ?>
                        <a href="nueva_escena.php" class="btn btn-primary mt-3">Escena nueva</a>
                    </div>
                </div>
            </div>
            <?php else: ?>
            <div align="center" class="mt-5">
                <h2 class="mt-3"><?= $i_control_texto1 ?></h2>
                <h3 class="mt-3"><?= $i_control_texto2 ?></h3>
                <a href="nueva_escena.php" class="btn btn-primary mt-3 mb-3"><?= $i_control_boton1 ?></a>
            </div>
            <?php endif;?>
        </div>

        <div class="tab-pane fade" id="camaras" role="tabpanel" aria-labelledby="camaras_tab">
            <?php if(!empty($camaras)) : ?>
            <div class="row">
                <?php foreach($camaras as $camara) :?>
                <div class="offset-1 col-10">
                    <p>Aqui van las camaras</p>
                </div>
                <?php endforeach; ?>
            </div>
            <?php else: ?>
            <div align="center" class="mt-5">
                <h2 class="mt-3"><?= $i_control_texto3 ?></h2>
                <h3 class="mt-3"><?= $i_control_texto4 ?></h3>
                <a href="contacto.php" class="btn btn-primary mt-3 mb-3"><?= $i_control_boton2 ?></a>
            </div>
            <?php endif; ?>
        </div>
    </div>
</div>
<script>
    document.body.onload = cargarTab;
    let $dispositivos = $('.dispositivos_list');
    let $escenas = $('.scenes_list');
    for(let i=0; i<$dispositivos.length; i++) {
        $dispositivos.eq(i).click(seleccionarDisp);
    }
    for(let i=0; i<$escenas.length; i++) {
        $escenas.eq(i).click(seleccionarScn);
    }
    let dispositivo = "", escena = "", accion = "";
    for (let i = 0; i<document.getElementsByClassName('nav-link').length; i++) {
        document.getElementsByClassName('nav-link')[i].onclick = guardarTab;
    }

    function guardarTab(event) {
        sessionStorage.setItem('active_tab_control', event.target.id);
    }

    function cargarTab() {
        let tab = sessionStorage.getItem('active_tab_control');
        if(tab == null) {
            tab = "dispositivos_tab";
        }
        let tab_p = tab.substring(0, tab.length - 4);
        document.getElementById(tab).classList.add('active');
        document.getElementById(tab).classList.add('show');
        document.getElementById(tab_p).classList.add('active');
        document.getElementById(tab_p).classList.add('show');
    }

    function seleccionarDisp(event) {
        dispositivo = event.target.nextElementSibling.value;
        seleccionar(dispositivo);
        for(let i=0; i<$dispositivos.length; i++) {
            if(event.target===$dispositivos[i]) {
                event.target.classList.add("disp_act");
            } else {
                if($dispositivos[i].classList.contains("disp_act")) {
                    $dispositivos[i].classList.remove("disp_act");
                }
            }
        }
    }

    function seleccionar(dispositivo) {
        let httpRequest = obtainXMLHttpRequest();
        httpRequest.open('POST', 'datos_dispositivos.php', true);
        httpRequest.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
        httpRequest.onreadystatechange = function() {
            if(httpRequest.readyState === 4) {
                if(httpRequest.status === 200) {
                    $('#datos_disp').remove();
                    $('#div_datos').append(httpRequest.responseText).children(':last').hide().fadeIn(900);
                    $('#controlador').click(cambiarEstado);
                    $('[name=prg_enviar]').eq(0).click(programarDisp);
                    //document.getElementsByName('prg_enviar')[0].onclick = programarDisp;
                }
            }
        };
        httpRequest.send('disp='+dispositivo);
    }

    function programarDisp() {
        let ok = true;
        if(document.getElementsByName('prg_date_start')[0].value==="") {
            document.getElementsByName('prg_date_start')[0].classList.add('is-invalid');
            ok = false;
        }
        if(document.getElementsByName('prg_hour_start')[0].value==="") {
            document.getElementsByName('prg_hour_start')[0].classList.add('is-invalid');
            ok = false;
        }
        if(document.getElementsByName('prg_temp')[0]) {
            if(document.getElementsByName('prg_temp')[0].value==="") {
                document.getElementsByName('prg_temp')[0].classList.add('is-invalid');
                ok = false;
            }
        }
        alert(ok);
        if (ok ===true) {
            let programa;
            let httpRequest = obtainXMLHttpRequest();
            httpRequest.open('POST', 'actualizar_dispositivo.php', true);
            httpRequest.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
            httpRequest.onreadystatechange = function() {
                if(httpRequest.readyState === 4) {
                    if(httpRequest.status === 200) {
                        if(httpRequest.responseText === "bien") {
                            seleccionar(dispositivo);
                        }

                    }
                }
            };
            if(!document.getElementsByName('prg_temp')[0]) {
                programa = new Program(dispositivo, document.getElementsByName('prg_date_start')[0].value, document.getElementsByName('prg_hour_start')[0].value, document.getElementsByName('prg_date_end')[0].value, document.getElementsByName('prg_hour_end')[0].value, document.getElementsByName('prg_temp_start')[0].value, document.getElementsByName('prg_temp_end')[0].value, null);
            } else {
                programa = new Program(dispositivo, document.getElementsByName('prg_date_start')[0].value, document.getElementsByName('prg_hour_start')[0].value, document.getElementsByName('prg_date_end')[0].value, document.getElementsByName('prg_hour_end')[0].value, document.getElementsByName('prg_tmp_start')[0].value, document.getElementsByName('prg_tmp_end')[0].value, document.getElementsByName('prg_temp')[0].value);
            }
            let datos = JSON.stringify(programa);
            httpRequest.send('programar='+datos);
        }
    }

    function cambiarEstado(event) {
        let httpRequest = obtainXMLHttpRequest();
        httpRequest.open('POST', 'actualizar_dispositivo.php', true);
        httpRequest.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
        httpRequest.onreadystatechange = function() {
            if(httpRequest.readyState === 4) {
                if(httpRequest.status === 200) {
                    if(httpRequest.responseText === "bien") {
                        if(event.target.src === "http://localhost/proyecto/imgs/off.png") {
                            event.target.src = "http://localhost/proyecto/imgs/on.png";
                        } else {
                            event.target.src = "http://localhost/proyecto/imgs/off.png";
                        }
                    }
                }
            }
        };
        httpRequest.send('activar='+dispositivo);
    }

    function seleccionarScn(event) {
        escena = event.target.nextElementSibling.value;
        seleccionarEscena(escena);
        for(let i=0; i<$escenas.length; i++) {
            if(event.target===$escenas[i]) {
                event.target.classList.add("disp_act");
            } else {
                if($escenas[i].classList.contains("disp_act")) {
                    $escenas[i].classList.remove("disp_act");
                }
            }
        }
    }

    function seleccionarEscena(escena) {
        let httpRequest = obtainXMLHttpRequest();
        httpRequest.open('POST', 'datos_dispositivos.php', true);
        httpRequest.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
        httpRequest.onreadystatechange = function() {
            if(httpRequest.readyState === 4) {
                if(httpRequest.status === 200) {
                    $('#datos_scn').remove();
                    $('#div_scns').append(httpRequest.responseText).children(':last').hide().fadeIn(900);
                    if(document.getElementById('scn_apagar').src==="http://localhost/proyecto/imgs/on.png") {
                        $('#scn_apagar').click(opcionesEscena);
                    }
                    if(document.getElementsByName('reuse_scn_btn')[0]) {
                        document.getElementsByName('reuse_scn_btn')[0].onclick = opcionesEscena;
                    }
                    $('#scn_modify').click(foo);
                    $('#scn_delete_conf').click(confirmarDelete);
                    $('[name=reuse_scn_date').change(activarReuse);
                }
            }
        };
        httpRequest.send('scn='+escena);
    }

    function foo() {
        alert("hola");
    }

    function activarReuse(event) {
        if(event.target.value!=="") {
            document.getElementsByName('reuse_scn_btn')[0].disabled = false;
        } else {
            document.getElementsByName('reuse_scn_btn')[0].disabled = true;
        }
    }

    function confirmarDelete(event) {

        let difuminador = document.createElement('div');
        difuminador.setAttribute('id', 'difuminador');

        let divisor = document.createElement('div');
        divisor.setAttribute('class', 'formulario_scn');

        let parrafo = document.createElement('p');
        let texto = document.createTextNode("Ha seleccionado eliminar la escena.");
        parrafo.appendChild(texto);
        let parrafo2 = document.createElement('p');
        let texto2 = document.createTextNode("¿Desea continuar?");
        parrafo2.appendChild(texto2);

        let div_btn = document.createElement('div');
        div_btn.setAttribute('id', 'div_btns');

        let btn1 = document.createElement('input');
        btn1.setAttribute('type', 'button');
        btn1.setAttribute('class', 'btn btn-primary mr-3');
        btn1.setAttribute('id', 'scn_delete');
        btn1.setAttribute('value', 'Aceptar');

        let btn2 = document.createElement('input');
        btn2.setAttribute('type', 'button');
        btn2.setAttribute('class', 'btn btn-danger');
        btn2.setAttribute('id', 'scn_delete_cancel');
        btn2.setAttribute('value', 'Cancelar');

        div_btn.appendChild(btn1);
        div_btn.appendChild(btn2);

        divisor.appendChild(parrafo);
        divisor.appendChild(parrafo2);
        divisor.appendChild(div_btn);

        document.body.appendChild(divisor);
        document.body.appendChild(difuminador);

        $('#scn_delete_cancel').click(cancelarDel);
        $('#scn_delete').click(opcionesEscena);

    }

    function cancelarDel() {
        document.body.removeChild(document.getElementsByClassName('formulario_scn')[0]);
        document.body.removeChild(document.getElementById('difuminador'));
    }

    function opcionesEscena(event) {
        if(document.getElementById('difuminador')) {
            cancelarDel();
        }
        let httpRequest = obtainXMLHttpRequest();
        httpRequest.open('POST', 'actualizar_dispositivo.php', true);
        httpRequest.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
        httpRequest.onreadystatechange = function() {
            if(httpRequest.readyState === 4) {
                if(httpRequest.status === 200) {
                    if(httpRequest.responseText === "apagado") {
                        document.getElementById('scn_apagar').src = "http://localhost/proyecto/imgs/off.png";
                        let date = document.createElement('input');
                        date.setAttribute('type', 'date');
                        date.setAttribute('name', 'reuse_scn_date');
                        date.setAttribute('class', 'form-control mb-3');

                        let button = document.createElement('button');
                        button.setAttribute('type', 'button');
                        button.setAttribute('name', 'reuse_scn_btn');
                        button.setAttribute('class', 'btn btn-primary mb-3');
                        button.setAttribute('id', 'scn_update');
                        button.setAttribute('disabled', 'true');
                        let btn_text = document.createTextNode('Actualizar escena');
                        button.appendChild(btn_text);

                        document.getElementById('datos_scn').insertBefore(button, document.getElementById('scn_apagar').nextSibling );
                        document.getElementById('datos_scn').insertBefore(date, document.getElementById('scn_apagar').nextSibling);

                        $('[name=reuse_scn_date').change(activarReuse);
                        $('[name=reuse_scn_btn').click(opcionesEscena);

                    } else if(httpRequest.responseText === "eliminado") {
                        $('#datos_scn').remove();
                        for(let i = 0; i<document.getElementsByClassName('scenes_list').length; i++) {
                            if (document.getElementsByClassName('scenes_list')[i].classList.contains('disp_act')) {
                                document.getElementsByClassName('scenes_list')[i].parentNode.removeChild(document.getElementsByClassName('scenes_list')[i].nextElementSibling);
                                document.getElementsByClassName('scenes_list')[i].parentNode.removeChild(document.getElementsByClassName('scenes_list')[i]);
                            }
                        }
                    } else if(httpRequest.responseText === "actualizado") {
                        seleccionarEscena(escena);
                    }
                }
            }
        };
        let date = "";
        if(document.getElementsByName("reuse_scn_date")[0]) {
            date = document.getElementsByName("reuse_scn_date")[0].value;
        }
        let escena_datos = new Scene(escena, event.target.id, date);
        escena_datos = JSON.stringify(escena_datos);
        httpRequest.send('escena='+escena_datos);
    }

    function Program(id_disp, dia_ini, hora_ini, dia_fin, hora_fin, temp_ini, temp_fin, temp) {
        this.id_disp = id_disp;
        this.dia_ini = dia_ini;
        this.hora_ini = hora_ini;
        this.dia_fin = dia_fin;
        this.hora_fin = hora_fin;
        this.temp_ini = temp_ini;
        this.temp_fin = temp_fin;
        this.temp =  temp;
    }

    /*function Escena(id_escena, fecha) {
        this.id_escena = id_escena;
        this.fecha = fecha;
    }*/

    function Scene(id_escena, accion, fecha) {
        this.id_escena = id_escena;
        this.accion = accion;
        this.fecha = fecha;
    }

</script>