<div class="container-fluid mt-2">
    <div class="row">
        <div class="col-6 offset-3">
            <select class="form-control">
                <option disabled>Elige el mes del que quieres ver tus gáficas de uso</option>
                <option disabled>--------------------------------------------------------</option>
                <option value="actual" selected >Mes actual</option>
                <?php foreach($meses as $mes) {
                    $dateObj = DateTime::createFromFormat('!m', $mes['mes']);
                    $mes_act = $dateObj->format('F');?>
                <option value="<?= $mes['mes']."-".$mes['anyo'] ?>"><?= $mes_act ." ". $mes['anyo'] ?></option>
                <?php } ?>
                <option value="total">Total</option>
            </select>
        </div>
        <div class="col-12 col-md-5 offset-md-1 graficas mt-5">
            <div id="chartEncendidos"></div>
            <div class="cover1"></div>
        </div>
        <div class="col-12 col-md-5 graficas mt-5"">
            <div id="chartTiempos"></div>
            <div class="cover1"></div>
        </div>
    </div>
</div>
<script>
    document.getElementsByTagName('select')[0].onchange = cargarGraficas;
    //document.body.onload = cargarGraficas;
    $(document).ready(cargarGraficas);

    function cargarGraficas() {
        //alert(event.target.value);
        let valor = document.getElementsByTagName('select')[0].value;
        let dispositivos;
        let httpRequest = obtainXMLHttpRequest();
        httpRequest.open('POST', 'gest_graficas.php', true);
        httpRequest.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
        httpRequest.onreadystatechange = function () {
            if (httpRequest.readyState === 1) {
                cargando();
            }
            if (httpRequest.readyState === 4) {
                if (httpRequest.status === 200) {
                    quitarCargando();
                    dispositivos = JSON.parse(httpRequest.responseText);

                    let dataPoints = [];
                    let chart = new CanvasJS.Chart("chartEncendidos", {
                        title: {
                            text: "Cantidad de veces encendido por dispositivos (mensual)",
                            fontFamily: "Calibri"
                        },
                        data: [
                            {
                                type: "bar",
                                dataPoints: dataPoints
                            }]
                    });
                    for (let i = 0; i < dispositivos.length; i++) {
                        dataPoints.push({
                            label: dispositivos[i]['habitacion'] + " - " + dispositivos[i]['nombre'],
                            y: parseInt(dispositivos[i]['num_encendidos'])
                        });
                    }

                    let dataPoints2 = [];
                    let chart2 = new CanvasJS.Chart("chartTiempos", {
                        title: {
                            text: "Tiempo encendido por dispositivos (mensual)",
                            fontFamily: "Calibri"
                        },
                        data: [
                            {
                                type: "pie",
                                dataPoints: dataPoints2
                            }]
                    });
                    for (let i = 0; i < dispositivos.length; i++) {
                        dataPoints2.push({
                            label: dispositivos[i]['habitacion'] + " - " + dispositivos[i]['nombre'],
                            y: parseInt(dispositivos[i]['tiempo_encendido'])
                        });
                    }

                    chart.render();
                    chart2.render();

                }
            }
        };
        httpRequest.send('graph=' + valor);
    }
</script>