<div class="container-fluid mt-5">
    <div class="row">
        <div class="col-12 col-md-5 offset-md-1 graficas" >
            <div id="chartEncendidos"></div>
        </div>
        <div class="col-12 col-md-5 graficas" >
            <div id="chartTiempos"></div>
        </div>
    </div>
</div>
<script>
    window.onload = function () {
        let dispositivos = JSON.parse('<?= $disp ?>');
        let dataPoints = [];
        let chart = new CanvasJS.Chart("chartEncendidos", {
            title:{
                text: "Cantidad de veces encendido por dispositivos",
                fontFamily: "Calibri"
            },
            data: [
                {
                    type: "bar",
                    dataPoints: dataPoints
                }]
        });
        for (let i = 0; i<dispositivos.length; i++) {
            dataPoints.push({ label : dispositivos[i]['habitacion'] + " - " + dispositivos[i]['nombre'], y : parseInt(dispositivos[i]['num_encendidos']) });
        }

        let dataPoints2 = [];
        let chart2 = new CanvasJS.Chart("chartTiempos", {
            title:{
                text: "Tiempo encendido por dispositivos",
                fontFamily: "Calibri"
            },
            data: [
                {
                    type: "pie",
                    dataPoints: dataPoints2
                }]
        });
        for (let i = 0; i<dispositivos.length; i++) {
            dataPoints2.push({ label : dispositivos[i]['habitacion'] + " - " + dispositivos[i]['nombre'], y : parseInt(dispositivos[i]['tiempo_encendido']) });
        }
        chart.render();
        chart2.render();
    }

</script>