<div class="container mt-4">
    <div class="row">
        <div class="col-3">
            <label>Fecha inicio</label>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1"><i class="far fa-calendar-alt"></i></span>
                </div>
                <input type="date" class="form-control" name="log_start">
                <div class="invalid-feedback"><?= $i_guser_error2 ?></div>
            </div>
        </div>
        <div class="col-3">
            <label>Fecha fin</label>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1"><i class="far fa-calendar-alt"></i></span>
                </div>
                <input type="date" class="form-control" name="log_end">
                <div class="invalid-feedback"><?= $i_guser_error2 ?></div>
            </div>
        </div>
        <div class="col-3">
            <label>Posicion/escena</label>
            <select class="form-control" name="log_hab">
                <option selected disabled>Elige habitacion/escena</option>
                <option disabled>-----------------------</option>
                <option value="all">Todos</option>
                <?php foreach($hab_logs as $habs) : ?>
                <option value="<?= $habs['habitacion'] ?>"><?= $habs['habitacion'] ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="col-3">
            <button type="button" class="btn btn-primary hvr-icon-rotate" id="btn_log_reset"><i class="fas fa-redo hvr-icon"></i></button>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-12 code_container">
            <?php if (!empty($logs)) : ?>
            <code>
                <?php foreach ($logs as $log) : ?>
                    <span><?= $log['fecha'] . " " . $log['hora'] . "  -->  " . $log['info'] ?></span><br>
                <?php endforeach; ?>
            </code>
        </div>
        <form action="" method="post">
            <button class="btn btn-success mt-3" name="export_xls"><i class="far fa-file-excel mr-1"></i> Exportar log
            </button>
        </form>
        <?php else: ?>
        <div align="center" class="mt-5">
            <h2 class="mt-3">No has usado ningun dispositivo todavia</h2>
            <h3 class="mt-3">Empieza a sacarle provecho al control que tienes sobre tu casa al alcance de tu bolsillo</h3>
            <a href="control.php" class="btn btn-primary mt-3 mb-3"><?= $i_control_boton1 ?></a>
        </div>
    </div>
    <?php endif; ?>
</div>
</div>
<script>
    let f_inicio = "", f_fin = "", habitacion = "";
    document.getElementsByName('log_start')[0].onchange = actualizarInicio;
    document.getElementsByName('log_end')[0].onchange = actualizarFin;
    document.getElementsByName('log_hab')[0].onchange = actualizarHab;
    document.getElementById('btn_log_reset').onclick = limpiarLog;

    function limpiarLog() {
        document.location.href = "historial.php";
    }

    function actualizarInicio(event) {
        f_inicio = event.target.value;
        actualizarLog();
    }

    function actualizarFin(event) {
        f_fin = event.target.value;
        actualizarLog();
    }

    function actualizarHab(event) {
        habitacion = event.target.value;
        actualizarLog();
    }

    function actualizarLog() {
        let httpRequest = obtainXMLHttpRequest();
        httpRequest.open('POST', 'actualizar_log.php', true);
        httpRequest.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
        httpRequest.onreadystatechange = function () {
            if (httpRequest.readyState === 1) {
                cargando();
            }
            if (httpRequest.readyState === 4) {
                if (httpRequest.status === 200) {
                    quitarCargando();
                }
                document.getElementsByClassName('code_container')[0].removeChild(document.getElementsByTagName('code')[0]);
                //document.getElementsByClassName('code_container')[0].append(httpRequest.responseText);
                $('.code_container').eq(0).append(httpRequest.responseText);
            }
        };
        let datos = new Datos_log(f_inicio, f_fin, habitacion);
        datos = JSON.stringify(datos);
        httpRequest.send('log_query=' + datos);
    }

    function Datos_log(f_inicio, f_fin, habitacion) {
        this.f_inicio = f_inicio;
        this.f_fin = f_fin;
        this.habitacion = habitacion;
    }


</script>