<div class="container mt-4">
    <div class="row">
        <div class="col-12 code_container">
            <?php if (!empty($logs)) : ?>
            <code>
                <?php foreach ($logs as $log) : ?>
                    <span><?= $log['fecha'] . " " . $log['hora'] . "  -->  " . $log['info'] ?></span><br>
                <?php endforeach; ?>
            </code>
        </div>
        <form action="" method="post">
            <button class="btn btn-success mt-3" name="export_xls"><i class="far fa-file-excel mr-1"></i> Exportar log
            </button>
        </form>
        <?php else: ?>
        <div align="center" class="mt-5">
            <h2 class="mt-3">No has usado ningun dispositivo todavia</h2>
            <h3 class="mt-3">Empieza a sacarle provecho al control que tienes sobre tu casa al alcance de tu bolsillo</h3>
            <a href="control.php" class="btn btn-primary mt-3 mb-3"><?= $i_control_boton1 ?></a>
        </div>
    </div>
    <?php endif; ?>
</div>
</div>