<div class="container col-12 col-md-8">
    <div class="row">
        <div class="col-12 imagen_index">
            <?php if($hora>=00 && $hora<=05): ?>
                <img src="imgs/index4.jpg" class="img-fluid img-index">
            <?php elseif($hora>=06 && $hora<=11): ?>
                <img src="imgs/index1.jpg" class="img-fluid img-index">
            <?php elseif($hora>=12 && $hora<=17): ?>
                <img src="imgs/index2.jpg" class="img-fluid img-index">
            <?php elseif($hora>=18 && $hora<=23): ?>
                <img src="imgs/index3.jpg" class="img-fluid img-index">
            <?php endif; ?>
            <div id="index_title">
                <h1>SMART LIVING</h1>
                <hr>
                <h3>Donde tu casa cobra vida</h3>
                <a href="contacto.php" class="btn btn-dark mt-3">Contacta con nosotros</a>
            </div>
        </div>
    </div>
</div>