<div class="container-fluid col-12">
    <div class="row">
        <div class="col-12 imagen_index mb-3">
            <?php if($hora>=00 && $hora<=05): ?>
                <img src="imgs/index4.jpg" class="img-fluid img-index">
            <?php elseif($hora>=06 && $hora<=11): ?>
                <img src="imgs/index1.jpg" class="img-fluid img-index">
            <?php elseif($hora>=12 && $hora<=17): ?>
                <img src="imgs/index2.jpg" class="img-fluid img-index">
            <?php elseif($hora>=18 && $hora<=23): ?>
                <img src="imgs/index3.jpg" class="img-fluid img-index">
            <?php endif; ?>
            <div id="index_title">
                <h1>SMART LIVING</h1>
                <hr>
                <h3><?= $i_index_texto1 ?></h3>
                <a href="contacto.php" class="btn btn-dark mt-3 hvr-bubble-float-bottom2"><?= $i_index_texto2 ?></a>
            </div>
        </div>
    </div>
</div>
<div class="container col-12 col-md-8">
    <div class="row">
        <div class="col-12 col-lg-4" id="info_tiempo">
            <h3 class="mt-3"><?= $i_index_texto3 ?></h3>
            <p class="text-muted"><?= $i_index_texto4 ?></p>
            <select class="form-control mt-3" id="selec_comunidad">
                <option selected disabled class="text-muted"><?= $i_index_select1 ?></option>
                <option disabled class="text-muted">------------------------------</option>
                <?php foreach($comunidades as $comunidad): ?>
                <option value="<?= $comunidad['id'] ?>"><?= $comunidad['comunidad'] ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="col-12 col-lg-8 mt-3" id="datos_tiempo">

        </div>
    </div>
    <div class="row">
        <div class="col-12 mt-5">
            <iframe id="videoYT" width="100%" src="https://www.youtube.com/embed/UPGir81FUpY" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
    </div>
</div>
<div class="container-fluid mt-5">
    <div class="row">
        <div class="col-12 col-md-6">
            <i class="fas fa-quote-left hvr-grow-rotate"></i>
            <div class="quote_container">
                <hr>
                <p>"La mejor empresa para que tu casa funcione de la forma mas eficiente posible"</p>
                <hr>
                <i>New York Times</i>
            </div>
        </div>
        <div class="col-12 col-md-6">
            <i class="fas fa-quote-left hvr-grow-rotate"></i>
            <div class="quote_container">
                <hr>
                <p>"Opiniones buenas de mentira para hacer que la pagina quede mejor de lo que es ya en realidad"</p>
                <hr>
                <i>Tim Cook - Apple CEO</i>
            </div>
        </div>
    </div>
</div>
<div class="container mt-5">
    <div class="row pide_presupuesto">
        <div class="col-12 col-lg-6">
            <img src="imgs/dibujo.jpg" style="width: 100%" >
        </div>
        <div class="col-12 col-lg-6 info_presupuesto align-self-center">
            <img src="imgs/list1.png" class="hvr-grow"><p>Cuidamos el medio ambiente</p>
            <img src="imgs/list2.png" class="hvr-grow"><p>Utilizamos tecnologia puntera</p>
            <img src="imgs/list3.png" class="hvr-grow"><p>Cuidamos a nuestros clientes</p>
            <img src="imgs/list4.png" class="hvr-grow"><p>Cumplimos nuestras promesas</p>
            <img src="imgs/list5.png" class="hvr-grow"><p>Garantizamos tu seguridad</p>
            <img src="imgs/list6.png" class="hvr-grow"><p>Accede desde donde quieras</p>
        </div>
    </div>
</div>


<!--
<div class="container">
    <div class="row">
        <div class="col-12">
            <iframe width="550" height="400" src="https://prezi.com/view/0XSkuukVNvlCd7ykEczP/embed" webkitallowfullscreen="1" mozallowfullscreen="1" allowfullscreen="1"></iframe>
        </div>
    </div>
</div>
-->

<!--
<div class="container mt-3">
        <div class="row">

        <div class="col-8">

        </div>
        <div class="col-4">
            <iframe src="https://open.spotify.com/embed/user/mnd1k44b3c2v6qbgrs08r3uod/playlist/7r15xKvOAhAU8dTgaZy6YI?si=mrY_N0wPRt6HcZAyPwEXSA" width="100%" height="380" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
            <iframe src="https://open.spotify.com/follow/1/?uri=spotify:user:mnd1k44b3c2v6qbgrs08r3uod&size=detail&theme=light" width="300" height="56" scrolling="no" frameborder="0" style="border:none; overflow:hidden;" allowtransparency="true"></iframe>
        </div>
    </div>
</div>
-->
<a href="#" id="go_up" class="hvr-icon-up" onclick="topFunction()"><i class="fas fa-chevron-up hvr-icon"></i></a>
<script>
    window.onscroll = function() {scrollFunction()};
    document.body.onload = resizeIframe;
    document.body.onresize = resizeIframe;
    $('#selec_comunidad').change(cargarProvincias);
    /* let t1=0; */

    function resizeIframe() {
        let anchura = document.getElementById('videoYT').scrollWidth;
        document.getElementById('videoYT').height = anchura*0.5625;
    }

    function scrollFunction() {
        if (document.body.scrollTop > 500 || document.documentElement.scrollTop > 500) {
            document.getElementById("go_up").style.display = "block";
        } else {
            document.getElementById("go_up").style.display = "none";
        }
    }

    function topFunction() {
        $('html, body').animate({scrollTop:0}, 'slow');
    }

    function cargarProvincias(event) {
        let httpRequest = new obtainXMLHttpRequest();
        httpRequest.open('POST', 'gest_tiempo.php', true);
        httpRequest.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
        httpRequest.onreadystatechange = function() {
            if(httpRequest.readyState === 4) {
                if(httpRequest.status === 200) {
                    if(document.getElementById('select_provincia')) {
                        document.getElementById('info_tiempo').removeChild(document.getElementById('select_provincia'));
                    }
                    if(document.getElementById('select_municipio')) {
                        document.getElementById('info_tiempo').removeChild(document.getElementById('select_municipio'));
                    }
                    $('#info_tiempo').append(httpRequest.responseText);
                    $('#select_provincia').change(cargarMunicipios);
                }
            }
        };
        httpRequest.send('comunidad='+event.target.value);
    }

    function cargarMunicipios(event) {
        let httpRequest = new obtainXMLHttpRequest();
        httpRequest.open('POST', 'gest_tiempo.php', true);
        httpRequest.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
        httpRequest.onreadystatechange = function() {
            if(httpRequest.readyState === 4) {
                if(httpRequest.status === 200) {
                    if(document.getElementById('select_municipio')) {
                        document.getElementById('info_tiempo').removeChild(document.getElementById('select_municipio'));
                    }
                    $('#info_tiempo').append(httpRequest.responseText);
                    $('#select_municipio').change(cargarTiempo);
                }
            }
        };
        httpRequest.send('provincia='+event.target.value);
    }

    function cargarTiempo(event) {
        let httpRequest = new obtainXMLHttpRequest();
        httpRequest.open('POST', 'gest_tiempo.php', true);
        httpRequest.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
        httpRequest.onreadystatechange = function() {
            if(httpRequest.readyState === 4) {
                if(httpRequest.status === 200) {
                    if(document.getElementById('myTabContent')) {
                        document.getElementById('datos_tiempo').removeChild(document.getElementById('myTabContent'));
                        document.getElementById('datos_tiempo').removeChild(document.getElementById('myTab'));
                    }
                    $('#datos_tiempo').append(httpRequest.responseText);
                }
            }
        };
        httpRequest.send('municipio='+event.target.value);
    }

</script>