<div id="scroll_apartados">
    <ul class="list-group list-group-flush">
        <a href="#top" class="hvr-forward list_a">
            <li class="list-group-item hvr-underline-from-left2"><span>Arriba</span><i class="fas fa-chevron-right"></i></li>
        </a>
        <a href="#index_aboutus" class="hvr-forward list_a">
            <li class="list-group-item hvr-underline-from-left2"><span>Sobre nosotros</span><i class="fas fa-chevron-right"></i></li>
        </a>
        <a href="#index_video" class="hvr-forward list_a">
            <li class="list-group-item hvr-underline-from-left2"><span>Nuestro trabajo</span><i class="fas fa-chevron-right"></i></li>
        </a>
        <a href="#index_clientes" class="hvr-forward list_a">
            <li class="list-group-item hvr-underline-from-left2"><span>Nuestros clientes</span><i class="fas fa-chevron-right"></i></li>
        </a>
        <a href="#index_metas" class="hvr-forward list_a">
            <li class="list-group-item hvr-underline-from-left2"><span>Nuestras metas</span><i class="fas fa-chevron-right"></i></li>
        </a>
    </ul>
</div>
<div class="container-fluid col-12">
    <div class="row">
        <div class="col-12 imagen_index mb-3">
            <?php if ($hora >= 00 && $hora <= 05): ?>
                <img src="imgs/index4.jpg" class="img-fluid img-index">
            <?php elseif ($hora >= 06 && $hora <= 11): ?>
                <img src="imgs/index1.jpg" class="img-fluid img-index">
            <?php elseif ($hora >= 12 && $hora <= 17): ?>
                <img src="imgs/index2.jpg" class="img-fluid img-index">
            <?php elseif ($hora >= 18 && $hora <= 23): ?>
                <img src="imgs/index3.jpg" class="img-fluid img-index">
            <?php endif; ?>
            <div id="index_title">
                <h1>SMART LIVING</h1>
                <hr>
                <h3><?= $i_index_texto1 ?></h3>
                <a href="contacto.php" class="btn btn-dark mt-3 hvr-bubble-float-bottom2"><?= $i_index_texto2 ?></a>
            </div>
        </div>
    </div>
</div>
<div class="container col-12 col-md-8 pt-5 mb-5" id="index_aboutus">
    <div class="row">
        <div class="col-6">
            <h1>Controla tu casa desde cualquier dispositivo desde donde quieras</h1>
        </div>
        <div class="col-6">
            <img src="imgs/insert_block_efyb.svg" class="img-fluid">
        </div>
    </div>
    <div class="row mt-5 mb-5">
        <div class="col-6">
            <img src="imgs/predictive_analytics_kf9n.svg" class="img-fluid">
        </div>
        <div class="col-6">
            <h1>Observa a que dispositivos les das mas usos con gráficas dinámicas</h1>
        </div>
    </div>
</div>
<div class="container mt-5" id="index_video">
    <div class="row mt-5">
        <div class="col-12 mt-5">
            <iframe id="videoYT" width="100%" src="https://www.youtube.com/embed/UPGir81FUpY" frameborder="0"
                    allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                    allowfullscreen></iframe>
        </div>
    </div>
</div>
<div class="container-fluid pt-5" id="index_clientes">
    <div class="row mt-5">
        <div class="col-12 col-md-6 quotes">
            <i class="fas fa-quote-left hvr-grow-rotate"></i>
            <div class="quote_container">
                <hr>
                <p>"La mejor empresa para que tu casa funcione de la forma mas eficiente posible"</p>
                <hr>
                <i>New York Times</i>
            </div>
        </div>
        <div class="col-12 col-md-6 quotes">
            <i class="fas fa-quote-left hvr-grow-rotate"></i>
            <div class="quote_container">
                <hr>
                <p>"Opiniones buenas de mentira para hacer que la pagina quede mejor de lo que es ya en realidad"</p>
                <hr>
                <i>Tim Cook - Apple CEO</i>
            </div>
        </div>
    </div>
</div>
<div class="container pt-5" id="index_metas">
    <div class="row pide_presupuesto">
        <div class="col-12 col-lg-6">
            <img src="imgs/dibujo.jpg" style="width: 100%">
        </div>
        <div class="col-12 col-lg-6 info_presupuesto align-self-center">
            <img src="imgs/list1.png" class="hvr-grow">
            <p>Cuidamos el medio ambiente</p>
            <img src="imgs/list2.png" class="hvr-grow">
            <p>Utilizamos tecnologia puntera</p>
            <img src="imgs/list3.png" class="hvr-grow">
            <p>Cuidamos a nuestros clientes</p>
            <img src="imgs/list4.png" class="hvr-grow">
            <p>Cumplimos nuestras promesas</p>
            <img src="imgs/list5.png" class="hvr-grow">
            <p>Garantizamos tu seguridad</p>
            <img src="imgs/list6.png" class="hvr-grow">
            <p>Accede desde donde quieras</p>
        </div>
    </div>
</div>

<!--
<div class="container">
    <div class="row">
        <div class="col-12">
            <iframe width="550" height="400" src="https://prezi.com/view/0XSkuukVNvlCd7ykEczP/embed" webkitallowfullscreen="1" mozallowfullscreen="1" allowfullscreen="1"></iframe>
        </div>
    </div>
</div>
-->

<!--
<div class="container mt-3">
        <div class="row">

        <div class="col-8">

        </div>
        <div class="col-4">
            <iframe src="https://open.spotify.com/embed/user/mnd1k44b3c2v6qbgrs08r3uod/playlist/7r15xKvOAhAU8dTgaZy6YI?si=mrY_N0wPRt6HcZAyPwEXSA" width="100%" height="380" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
            <iframe src="https://open.spotify.com/follow/1/?uri=spotify:user:mnd1k44b3c2v6qbgrs08r3uod&size=detail&theme=light" width="300" height="56" scrolling="no" frameborder="0" style="border:none; overflow:hidden;" allowtransparency="true"></iframe>
        </div>
    </div>
</div>
-->

<a href="#" id="go_up" class="hvr-icon-up" onclick="topFunction()"><i class="fas fa-chevron-up hvr-icon"></i></a>
<script>
    $('a[href*="#"]').not('[href="#"]').not('[href="#0"]').click(function (event) {
        if (location.pathname.replace(/^\//, '') === this.pathname.replace(/^\//, '') && location.hostname === this.hostname) {
            var target = $(this.hash);
            target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
            if (target.length) {
                event.preventDefault();
                $('html, body').animate({
                    scrollTop: target.offset().top
                }, 1500, function () {
                    var $target = $(target);
                    $target.focus();
                    if ($target.is(":focus")) {
                        return false;
                    } else {
                        $target.attr('tabindex', '-1');
                        $target.focus();
                    };
                });
            }
        }
    });
    window.onscroll = function () {
        scrollFunction()
    };
    $(document).ready(resizeIframe);
    //document.body.onload = resizeIframe;
    document.body.onresize = resizeIframe;

    function resizeIframe() {
        let anchura = document.getElementById('videoYT').scrollWidth;
        document.getElementById('videoYT').height = anchura * 0.5625;
    }

    function scrollFunction() {
        if (document.body.scrollTop > 500 || document.documentElement.scrollTop > 500) {
            document.getElementById("go_up").style.display = "block";
        } else {
            document.getElementById("go_up").style.display = "none";
        }
    }

    function topFunction() {
        $('html, body').animate({scrollTop: 0}, 'slow');
    }

    /*function cargarProvincias(event) {
        let httpRequest = new obtainXMLHttpRequest();
        httpRequest.open('POST', 'gest_tiempo.php', true);
        httpRequest.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
        httpRequest.onreadystatechange = function() {
            if(httpRequest.readyState === 4) {
                if(httpRequest.status === 200) {
                    if(document.getElementById('select_provincia')) {
                        document.getElementById('info_tiempo').removeChild(document.getElementById('select_provincia'));
                    }
                    if(document.getElementById('select_municipio')) {
                        document.getElementById('info_tiempo').removeChild(document.getElementById('select_municipio'));
                    }
                    $('#info_tiempo').append(httpRequest.responseText);
                    $('#select_provincia').change(cargarMunicipios);
                }
            }
        };
        httpRequest.send('comunidad='+event.target.value);
    }*/

    /*function cargarMunicipios(event) {
        let httpRequest = new obtainXMLHttpRequest();
        httpRequest.open('POST', 'gest_tiempo.php', true);
        httpRequest.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
        httpRequest.onreadystatechange = function() {
            if(httpRequest.readyState === 4) {
                if(httpRequest.status === 200) {
                    if(document.getElementById('select_municipio')) {
                        document.getElementById('info_tiempo').removeChild(document.getElementById('select_municipio'));
                    }
                    $('#info_tiempo').append(httpRequest.responseText);
                    $('#select_municipio').change(cargarTiempo);
                }
            }
        };
        httpRequest.send('provincia='+event.target.value);
    }*/

    /*function cargarTiempo(event) {
        let httpRequest = new obtainXMLHttpRequest();
        httpRequest.open('POST', 'gest_tiempo.php', true);
        httpRequest.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
        httpRequest.onreadystatechange = function() {
            if(httpRequest.readyState === 4) {
                if(httpRequest.status === 200) {
                    if(document.getElementById('myTabContent')) {
                        document.getElementById('datos_tiempo').removeChild(document.getElementById('myTabContent'));
                        document.getElementById('datos_tiempo').removeChild(document.getElementById('myTab'));
                    }
                    $('#datos_tiempo').append(httpRequest.responseText);
                }
            }
        };
        httpRequest.send('municipio='+event.target.value);
    }*/

</script>