<div class="container mt-4">
    <form action="control.php" method="post" id="form_scn">
        <div class="row mt-4">
            <div class="col-6">
                <label>Nombre de la escena</label>
                <input type="text" name="scn_name" class="form-control">
                <div class="invalid-feedback"><?= $i_guser_error2 ?></div>
            </div>
            <div class="col-6">
                <label>Fecha inicio</label>
                <input type="date" name="scn_date" class="form-control">
                <div class="invalid-feedback"><?= $i_guser_error2 ?></div>
            </div>
        </div>
        <div class="row mt-4 row_disp">
            <div class="col-2">
                <label>Dispositivo</label>
                <select class="form-control" name="scn_disp_name[]">
                    <option disabled selected value="no">Elige el dispositivo</option>
                    <option disabled value="no">----------------------</option>
                    <?php foreach ($dispositivos as $dispositivo) {
                        if ($dispositivo['temperatura'] != null) :?>
                            <option value="<?= $dispositivo['id'] ?>" class="has_temp"><?= $dispositivo['habitacion'] . ' - ' . $dispositivo['nombre'] ?></option>
                        <?php else: ?>
                            <option value="<?= $dispositivo['id'] ?>"><?= $dispositivo['habitacion'] . ' - ' . $dispositivo['nombre'] ?></option>
                        <?php endif;
                    } ?>

                </select>
                <div class="invalid-feedback"><?= $i_guser_error2 ?></div>
            </div>
            <div class="col-2">
                <label>Hora inicio</label>
                <input type="time" class="form-control" name="scn_disp_start[]" disabled>
                <div class="invalid-feedback"><?= $i_guser_error2 ?></div>
            </div>
            <div class="col-2">
                <label>Hora fin</label>
                <input type="time" class="form-control" name="scn_disp_end[]" disabled>
            </div>
            <div class="col-2">
                <label>Temperatura inicio</label>
                <input type="number" min="0" class="form-control" name="scn_disp_tmp_start[]" placeholder="0" disabled>
                <div class="invalid-feedback"><?= $i_guser_error2 ?></div>
            </div>
            <div class="col-2">
                <label>Temperatura fin</label>
                <input type="number" min="0" class="form-control" name="scn_disp_tmp_end[]" placeholder="0" disabled>
                <div class="invalid-feedback"><?= $i_guser_error2 ?></div>
            </div>
            <div class="col-2">
                <label>Temperatura</label>
                <input type="number" min="0" class="form-control" name="scn_disp_tmp[]" placeholder="0" disabled>
                <div class="invalid-feedback"><?= $i_guser_error2 ?></div>
            </div>
        </div>
        <div class="row mt-4">
            <div class="form-check-inline ml-3">
                <div class="custom-control custom-checkbox my-1 mr-sm-2">
                    <input type="checkbox" class="custom-control-input" id="repeat1" name="scn_repeats[]" value="si">
                    <label class="custom-control-label" for="repeat1">Lunes</label>
                </div>
                <div class="custom-control custom-checkbox my-1 mr-sm-2">
                    <input type="checkbox" class="custom-control-input" id="repeat2" name="scn_repeats[]" value="si">
                    <label class="custom-control-label" for="repeat2">Martes</label>
                </div>
                <div class="custom-control custom-checkbox my-1 mr-sm-2">
                    <input type="checkbox" class="custom-control-input" id="repeat3" name="scn_repeats[]" value="si">
                    <label class="custom-control-label" for="repeat3">Miércoles</label>
                </div>
                <div class="custom-control custom-checkbox my-1 mr-sm-2">
                    <input type="checkbox" class="custom-control-input" id="repeat4" name="scn_repeats[]" value="si">
                    <label class="custom-control-label" for="repeat4">Jueves</label>
                </div>
                <div class="custom-control custom-checkbox my-1 mr-sm-2">
                    <input type="checkbox" class="custom-control-input" id="repeat5" name="scn_repeats[]" value="si">
                    <label class="custom-control-label" for="repeat5">Viernes</label>
                </div>
                <div class="custom-control custom-checkbox my-1 mr-sm-2">
                    <input type="checkbox" class="custom-control-input" id="repeat6" name="scn_repeats[]" value="si">
                    <label class="custom-control-label" for="repeat6">Sábado</label>
                </div>
                <div class="custom-control custom-checkbox my-1 mr-sm-2">
                    <input type="checkbox" class="custom-control-input" id="repeat7" name="scn_repeats[]" value="si">
                    <label class="custom-control-label" for="repeat7">Domingo</label>
                </div>
                <span class="mr-3 ml-2"> - </span>
                <div class="custom-control custom-checkbox my-1 mr-sm-2">
                    <input type="checkbox" class="custom-control-input" id="weekly" name="scn_weekly">
                    <label class="custom-control-label" for="weekly">Semanal</label>
                </div>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-12">
                <input type="button" name="new_scn_disp" value="Añadir dispositivo" class="btn btn-primary mr-3">
                <input type="button" name="del_scn_disp" value="Quitar dispositivo" class="btn btn-danger mr-3">
                <input type="button" name="scn_submit" value="Añadir escena" class="btn btn-success">
            </div>
        </div>
    </form>
</div>

<script>
    let row_disp = document.getElementsByClassName('row_disp')[0].cloneNode(true);
    document.getElementsByName('new_scn_disp')[0].onclick = nuevoDisp;
    document.getElementsByName('del_scn_disp')[0].onclick = quitarDisp;
    document.getElementsByName('scn_submit')[0].onclick = comprobarScnForm;
    for (let i = 0; i < document.getElementsByName('scn_disp_name[]').length; i++) {
        document.getElementsByName('scn_disp_name[]')[i].onchange = habilitarInputs;
    }

    //Añade un nuevo bloque de dispositivo
    function nuevoDisp(event) {
        event.target.parentNode.parentNode.parentNode.insertBefore(row_disp.cloneNode(true), event.target.parentNode.parentNode);
        for (let i = 0; i < document.getElementsByName('scn_disp_name[]').length; i++) {
            document.getElementsByName('scn_disp_name[]')[i].onchange = habilitarInputs;
        }
    }

    // Quita el ultimo bloque de dispositivo
    function quitarDisp(event) {
        if (document.getElementsByClassName('row_disp').length > 1) {
            event.target.parentNode.parentNode.parentNode.removeChild(document.getElementsByClassName('row_disp')[document.getElementsByClassName('row_disp').length - 1]);
        }
    }

    // Habilita los inputs al seleccionar un dispositivo
    function habilitarInputs(event) {
        for (let i = 0; i < document.getElementsByName('scn_disp_name[]').length; i++) {
            if (document.getElementsByName('scn_disp_name[]')[i] == event.target) {
                document.getElementsByName('scn_disp_start[]')[i].disabled = false;
                document.getElementsByName('scn_disp_end[]')[i].disabled = false;
                document.getElementsByName('scn_disp_tmp_start[]')[i].disabled = false;
                document.getElementsByName('scn_disp_tmp_end[]')[i].disabled = false;
                if (event.target.options[event.target.selectedIndex].classList.contains('has_temp')) {
                    document.getElementsByName('scn_disp_tmp[]')[i].disabled = false;
                } else {
                    document.getElementsByName('scn_disp_tmp[]')[i].disabled = true;
                }
            }
        }
    }

    // Comprueba que todos los datos del formulario esten rellenos
    function comprobarScnForm() {
        for (let i = 0; i < document.getElementsByTagName('input').length; i++) {
            document.getElementsByTagName('input')[i].classList.remove('is-invalid');
        }
        document.getElementsByTagName('select')[0].classList.remove('is-invalid');
        if (document.getElementById('texto_error')) {
            document.getElementById('texto_error').parentNode.removeChild(document.getElementById('texto_error'));
        }

        let ok = true;
        if (document.getElementsByName('scn_name')[0].value === "") {
            document.getElementsByName('scn_name')[0].classList.add('is-invalid');
            ok = false;
        }
        if (document.getElementsByName('scn_date')[0].value === "") {
            document.getElementsByName('scn_date')[0].classList.add('is-invalid');
            ok = false;
        }
        for (let i = 0; i < document.getElementsByName('scn_disp_name[]').length; i++) {
            if (document.getElementsByName('scn_disp_name[]')[i].value === "no") {
                document.getElementsByName('scn_disp_name[]')[i].classList.add('is-invalid');
                ok = false;
            }
        }
        for (let i = 0; i < document.getElementsByName('scn_disp_start[]').length; i++) {
            if (document.getElementsByName('scn_disp_start[]')[i].value === "" && document.getElementsByName('scn_disp_tmp_start[]')[i].value === "") {
                if (document.getElementsByName('scn_disp_start[]')[i].disabled === false) {
                    document.getElementsByName('scn_disp_start[]')[i].classList.add('is-invalid');
                    document.getElementsByName('scn_disp_tmp_start[]')[i].classList.add('is-invalid');
                    ok = false;
                }
            }
        }
        for (let i = 0; i < document.getElementsByName('scn_disp_tmp[]').length; i++) {
            if (document.getElementsByName('scn_disp_tmp[]')[i].value === "") {
                if (document.getElementsByName('scn_disp_tmp[]')[i].disabled === false) {
                    document.getElementsByName('scn_disp_tmp[]')[i].classList.add('is-invalid');
                    ok = false;
                }
            }
        }
        for (let i = 0; i < document.getElementsByName('scn_repeats[]').length; i++) {
            if (document.getElementsByName('scn_repeats[]')[i].checked === false) {
                document.getElementsByName('scn_repeats[]')[i].checked = true;
                document.getElementsByName('scn_repeats[]')[i].value = "no";
            }
        }
        if (ok === true) {
            for (let i = 0; i < document.getElementsByName('scn_disp_tmp[]').length; i++) {
                if (document.getElementsByName('scn_disp_tmp[]')[i].disabled === true) {
                    document.getElementsByName('scn_disp_tmp[]')[i].disabled = false;
                    document.getElementsByName('scn_disp_tmp[]')[i].value = null;
                }
            }
            document.getElementById('form_scn').submit();
        }
    }

</script>