<div class="container datos_perfil mt-3">
    <div class="row">
        <div class="col-12 col-md-5 col-lg-4 offset-md-1 offset-lg-2">
            <div class="row">
                <div class="col-12 col-sm-6 col-md-12">
                    <form action="perfil.php" method="post" enctype="multipart/form-data">
                        <img src="<?= $usuario->getFoto() ?>">
                        <br>
                        <button type="button" class="btn btn-secondary btn-sm mt-3" id="update_foto"><?= $i_perfil_boton1 ?></button>
                    </form>
                </div>
                <div class="col-12 col-sm-6 col-md-12">
                    <p class="mt-3"><?= $i_perfil_texto1 . $usuario->getNombre() ?> <i id="chg_name" class="btn btn-light far fa-edit"></i>
                    </p>
                    <p><?= $i_perfil_texto2 . $usuario->getEmail() ?> <i class="btn btn-light far fa-edit" id="chg_email"></i></p>
                    <p><?= $i_perfil_texto3 . count($dispositivos) ?></p>
                    <p><?= $i_perfil_texto4 . count($escenas) ?></p>
                    <p>Temperatura: <?= $tiempo['list'][0]['main']['temp'] ?> ºC</p>
                    <p>
                        <?php switch ($tiempo['list'][0]['weather'][0]['icon']) {
                            case "01d" :
                                ?>
                                <i class="wi wi-day-sunny hvr-pulse"></i>
                            <?php case "01n" : ?>
                                <i class="wi wi-night-clear hvr-pulse"></i>
                                <?php break;
                            case "02d" : ?>
                                <i class="wi wi-day-cloudy hvr-pulse"></i>
                                <?php break;
                            case "02n" : ?>
                                <i class="wi wi-night-alt-cloudy hvr-pulse"></i>
                                <?php break;
                            case "03d" :
                            case "03n" : ?>
                                <i class="wi wi-cloud hvr-pulse"></i>
                                <?php break;
                            case "04d" :
                            case "04n" : ?>
                                <i class="wi wi-cloudy hvr-pulse"></i>
                                <?php break;
                            case "09d" :
                            case "09n" : ?>
                                <i class="wi wi-rain hvr-pulse"></i>
                                <?php break;
                            case "10d" : ?>
                                <i class="wi wi-day-rain hvr-pulse"></i>
                                <?php break;
                            case "10n" : ?>
                                <i class="wi wi-night-alt-rain hvr-pulse"></i>
                                <?php break;
                            case "11d" :
                            case "11n" : ?>
                                <i class="wi wi-storm-showers hvr-pulse"></i>
                                <?php break;
                            case "13d" :
                            case "13n" : ?>
                                <i class="wi wi-snow hvr-pulse"></i>
                                <?php break;
                            case "50d" :
                            case "50n" : ?>
                                <i class="wi wi-fog hvr-pulse"></i>
                                <?php break;
                        } ?>
                        <?= $tiempo['list'][0]['weather'][0]['description'] ?></p>
                </div>
            </div>
        </div>
        <div class="col-12 col-md-5 col-lg-4 mt-5 mt-md-0">
            <ul class="nav nav-tabs nav-fill mb-3" id="myTab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link" id="disp_tab" data-toggle="tab" href="#disp" role="tab" aria-controls="disp" aria-selected="true"><?= $i_perfil_tab1 ?></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="prg_tab" data-toggle="tab" href="#prg" role="tab" aria-controls="prg" aria-selected="false"><?= $i_perfil_tab2 ?></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="scn_tab" data-toggle="tab" href="#scn" role="tab" aria-controls="scn" aria-selected="false"><?= $i_perfil_tab3 ?></a>
                </li>
            </ul>

            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade" id="disp" role="tabpanel" aria-labelledby="disp_tab">
                    <?php
                    foreach ($habitaciones as $habitacion) : ?>
                        <p class="habitacion_list"><?= $habitacion['habitacion'] ?></p>
                        <?php foreach ($dispositivos as $dispositivo) {
                            if ($dispositivo['habitacion'] == $habitacion['habitacion']):?>
                                <p class="dispositivos_list" data-container=".dispositivos_list" data-html="true"
                                   data-toggle="popover" data-placement="left" title="<?= $dispositivo['nombre'] ?>"
                                   data-content='<?= $i_perfil_popover1 . $habitacion['habitacion'] ?><br><?= $i_perfil_popover2 . $dispositivo['num_encendidos'] ?><br><?= $i_perfil_popover3 . $dispositivo['tiempo_encendido'] ?><br><?= $i_perfil_popover4 . $dispositivo['pin'] ?>'><?= $dispositivo['nombre'] ?></p>
                            <?php endif;
                        } endforeach; ?>
                    <?php if (!empty($camaras)) : ?>
                        <p class="habitacion_list"><?= $i_perfil_texto5 ?></p>
                        <?php foreach ($camaras as $camara): ?>
                            <p class="dispositivos_list"><?= $camara['nombre'] ?></p>
                        <?php endforeach;
                    endif; ?>
                </div>
                <div class="tab-pane fade" id="prg" role="tabpanel" aria-labelledby="prg_tab">
                    <?php if (!empty($programas)) : ?>
                        <p class="habitacion_list"><?= $i_perfil_texto6 ?></p>
                        <?php foreach ($programas as $programa) {
                            foreach ($dispositivos as $dispositivo) {
                                if ($programa['dispositivo_id'] == $dispositivo['id']):?>
                                    <p class="programas_list" data-container=".programas_list" data-html="true"
                                       data-toggle="popover" data-placement="left" title="<?= $dispositivo['nombre'] ?>"
                                       data-content='<?= $i_perfil_popover5 . $dispositivo['nombre'] ?><br><?= $i_perfil_popover8 . $programa['dia_inicio'] ?><br><?= $i_perfil_popover6 . $programa['hora_inicio'] ?><br><?= $i_perfil_popover9 . $programa['dia_fin'] ?><br><?= $i_perfil_popover7 . $programa['hora_fin'] ?>'><?= $dispositivo['nombre'] . " - " . $programa['dia_inicio'] . " - " . $programa['hora_inicio'] ?></p>
                                <?php endif;
                            }
                        }
                    else : ?>
                        <div style="text-align: center">
                            <p><?= $i_perfil_texto7 ?></p>
                            <a href="control.php" class="btn btn-primary"><?= $i_perfil_texto8 ?></a>
                        </div>
                    <?php endif; ?>
                </div>
                <div class="tab-pane fade" id="scn" role="tabpanel" aria-labelledby="scn_tab">
                    <?php if (!empty($escenas)) : ?>
                        <p class="habitacion_list"><?= $i_perfil_texto9 ?></p>
                        <?php foreach ($escenas as $escena) : ?>
                            <p class="escenas_list"><?= $escena['nombre'] ?></p>
                            <input type="hidden" name="id" value="<?= $escena['id'] ?>">
                        <?php endforeach;
                    else: ?>
                        <div style="text-align: center">
                            <p><?= $i_perfil_texto10 ?></p>
                            <a href="nueva_escena.php" class="btn btn-primary"><?= $i_perfil_texto11 ?></a>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(cargarTab);
    $('#update_foto').click(actualizarFoto);
    document.getElementById('chg_email').onclick = actualizarDato;
    document.getElementById('chg_name').onclick = actualizarDato;
    for (let i = 0; i < document.getElementsByClassName('nav-link').length; i++) {
        document.getElementsByClassName('nav-link')[i].onclick = guardarTab;
    }
    for (let i = 0; i < document.getElementsByClassName('escenas_list').length; i++) {
        document.getElementsByClassName('escenas_list')[i].onclick = verEscena;
    }

    function guardarTab(event) {
        if (sessionStorage.getItem('aceptadas') === "si") {
            sessionStorage.setItem('active_tab_perfil', event.target.id);
        }
    }

    function cargarTab() {
        let tab = sessionStorage.getItem('active_tab_perfil');
        if (tab == null) {
            tab = "disp_tab";
        }
        let tab_p = tab.substring(0, tab.length - 4);
        document.getElementById(tab).classList.add('active');
        document.getElementById(tab).classList.add('show');
        document.getElementById(tab_p).classList.add('active');
        document.getElementById(tab_p).classList.add('show');
    }

    function actualizarFoto(event) {
        let input = document.createElement('input');
        input.setAttribute('type', 'file');
        input.setAttribute('name', 'upd_foto');
        input.setAttribute('class', 'form-control-file mt-4');
        let salto = document.createElement('br');
        let input2 = document.createElement('input');
        input2.setAttribute('type', 'submit');
        input2.setAttribute('value', 'Cambiar');
        input2.setAttribute('class', 'btn btn-primary mt-1 mr-3');
        input2.setAttribute('disabled', 'true');
        input2.setAttribute('id', 'update_foto_sbm');
        let input3 = document.createElement('input');
        input3.setAttribute('type', 'button');
        input3.setAttribute('value', 'Cancelar');
        input3.setAttribute('class', 'btn btn-secondary mt-1');
        input3.setAttribute('id', 'cancel_foto');
        event.target.parentNode.appendChild(input);
        event.target.parentNode.appendChild(salto);
        event.target.parentNode.appendChild(input2);
        event.target.parentNode.appendChild(input3);
        $('[name=upd_foto]').eq(0).change(function () {
            $('#update_foto_sbm').prop('disabled', false);
        });
        $('#cancel_foto').click(cancelarFoto);
        $('#update_foto').unbind('click');
    }

    function cancelarFoto(event) {
        let foo = event.target.parentNode;
        foo.removeChild(foo.lastChild);
        foo.removeChild(foo.lastChild);
        foo.removeChild(foo.lastChild);
        foo.removeChild(foo.lastChild);
        $('#update_foto').click(actualizarFoto);
    }

    function actualizarDato(event) {
        //event.stopPropagation();
        event.target.onclick = "";
        //event.cancelBubble = true;
        let formulario = document.createElement('form');
        formulario.setAttribute('method', 'post');
        formulario.setAttribute('action', 'perfil.php');
        let input = document.createElement('input');
        input.setAttribute('type', 'text');
        if (event.target.id === "chg_name") {
            input.setAttribute('name', 'upd_name');
        } else {
            input.setAttribute('name', 'upd_email');
        }
        input.setAttribute('class', 'form-control mt-3');
        let salto = document.createElement('br');
        let subm = document.createElement('input');
        subm.setAttribute('type', 'submit');
        subm.setAttribute('value', 'Cambiar');
        subm.setAttribute('class', 'btn btn-primary mr-3');
        let cancel = document.createElement('input');
        cancel.setAttribute('type', 'button');
        cancel.setAttribute('value', 'Cancelar');
        cancel.setAttribute('class', 'btn btn-secondary cancel_update');
        formulario.appendChild(input);
        formulario.appendChild(salto);
        formulario.appendChild(subm);
        formulario.appendChild(cancel);
        event.target.parentNode.appendChild(formulario);
        for (let i = 0; i < document.getElementsByClassName('cancel_update').length; i++) {
            document.getElementsByClassName('cancel_update')[i].onclick = cancelar;
        }
        alert(event.target.id);
    }

    function verEscena(event) {
        window.location = "escena.php?id=" + event.target.nextElementSibling.value;
    }

    function cancelar(event) {
        event.target.parentNode.parentNode.removeChild(event.target.parentNode);
        document.getElementById('chg_name').onclick = actualizarDato;
        document.getElementById('chg_email').onclick = actualizarDato;
    }

    $('.dispositivos_list').on('click', function () {
        $('.dispositivos_list').not(this).popover('hide');
    });

    $('.programas_list').on('click', function () {
        $('.programas_list').not(this).popover('hide');
    });

    $('#prg_tab').on('click', function () {
        $('.dispositivos_list').popover('hide');
        $('.programas_list').popover('hide');
        $('.escenas_list').popover('hide');
    });

    $('#disp_tab').on('click', function () {
        $('.dispositivos_list').popover('hide');
        $('.programas_list').popover('hide');
        $('.escenas_list').popover('hide');
    });

    $('#scn_tab').on('click', function () {
        $('.dispositivos_list').popover('hide');
        $('.programas_list').popover('hide');
        $('.escenas_list').popover('hide');
    });

</script>