<div class="container datos_perfil mt-3">
    <div class="row">
        <div class="col-12 col-md-5 col-lg-4 offset-md-1 offset-lg-2">
            <div class="row">
                <div class="col-12 col-sm-6 col-md-12">
                    <form action="perfil.php" method="post" enctype="multipart/form-data">
                        <img src="<?= $usuario->getFoto() ?>">
                        <br>
                        <button type="button" class="btn btn-secondary btn-sm mt-3" id="update_foto"><?= $i_perfil_boton1 ?></button>
                    </form>
                </div>
                <div class="col-12 col-sm-6 col-md-12">
                    <p class="mt-3"><?= $i_perfil_texto1 ?><?= $usuario->getNombre() ?> <i class="btn btn-light far fa-edit"></i></p>
                    <p><?= $i_perfil_texto2 ?><?= $usuario->getEmail() ?></p>
                    <p><?= $i_perfil_texto3 ?><?= count($dispositivos) ?></p>
                    <p><?= $i_perfil_texto4 ?><?= count($escenas) ?></p>
                    <button type="button" class="btn btn-primary" id="btn_log"><?= $i_perfil_boton2 ?></button>
                </div>
            </div>
        </div>
        <div class="col-12 col-md-5 col-lg-4 mt-5 mt-md-0">
            <ul class="nav nav-tabs nav-fill mb-3" id="myTab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="disp_tab" data-toggle="tab" href="#disp" role="tab" aria-controls="disp" aria-selected="true"><?= $i_perfil_tab1 ?></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="prg_tab" data-toggle="tab" href="#prg" role="tab" aria-controls="prg" aria-selected="false"><?= $i_perfil_tab2 ?></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="scn_tab" data-toggle="tab" href="#scn" role="tab" aria-controls="scn" aria-selected="false"><?= $i_perfil_tab3 ?></a>
                </li>
            </ul>

            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="disp" role="tabpanel" aria-labelledby="disp_tab">
                    <?php
                    foreach ($habitaciones as $habitacion) : ?>
                        <p class="habitacion_list"><?= $habitacion['habitacion'] ?></p>
                        <?php foreach($dispositivos as $dispositivo) {
                            if($dispositivo['habitacion']==$habitacion['habitacion']):?>
                                <p class="dispositivos_list" data-container=".dispositivos_list" data-html="true" data-toggle="popover" data-placement="left" title="<?= $dispositivo['nombre'] ?>" data-content='<?= $i_perfil_popover1 ?><?= $habitacion['habitacion'] ?><br><?= $i_perfil_popover2 ?><?= $dispositivo['num_encendidos'] ?><br><?= $i_perfil_popover3 ?><?= $dispositivo['tiempo_encendido'] ?><br><?= $i_perfil_popover4 ?><?= $dispositivo['pin'] ?>'><?= $dispositivo['nombre'] ?></p>
                            <?php endif;
                        } endforeach; ?>
                    <?php if(!empty($camaras)) : ?>
                        <p class="habitacion_list"><?= $i_perfil_texto5 ?></p>
                        <?php foreach($camaras as $camara):?>
                            <p class="dispositivos_list"><?= $camara['nombre'] ?></p>
                        <?php endforeach;
                    endif;?>
                </div>
                <div class="tab-pane fade" id="prg" role="tabpanel" aria-labelledby="prg_tab">
                    <?php if(!empty($programas)) : ?>
                        <p class="habitacion_list"><?= $i_perfil_text6 ?></p>
                        <?php foreach($programas as $programa) {
                            foreach($dispositivos as $dispositivo) {
                                if($programa['dispositivo_id']==$dispositivo['id']):?>
                                <p class="programas_list" data-html="true" data-toggle="popover" data-placement="left" title="<?= $dispositivo['nombre'] ?>" data-content='<?= $i_perfil_popover5 ?><?= $dispositivo['nombre'] ?><br><?= $i_perfil_popover6 ?><?= $programa['inicio'] ?><br><?= $i_perfil_popover7 ?><?= $programa['fin'] ?>'><?= $dispositivo['nombre'] ?></p>
                                <?php endif;
                            }
                        }
                    else : ?>
                        <div style="text-align: center">
                            <p><?= $i_perfil_texto7 ?></p>
                            <a href="control.php" class="btn btn-primary"><?= $i_perfil_texto8 ?></a>
                        </div>
                    <?php endif; ?>
                </div>
                <div class="tab-pane fade" id="scn" role="tabpanel" aria-labelledby="scn_tab">
                    <?php if(!empty($escenas)) : ?>
                        <p class="habitacion_list"><?= $i_perfil_texto9 ?></p>
                        <?php foreach($escenas as $escena) : ?>
                            <p class="escenas_list" data-toggle="popover" data-trigger="focus" title="<?= $escena['nombre'] ?>" data-content="Datos"><?= $escena['nombre'] ?></p>
                        <?php endforeach;
                    else: ?>
                        <div style="text-align: center">
                            <p><?= $i_perfil_texto10 ?></p>
                            <a href="control.php" class="btn btn-primary"><?= $i_perfil_texto11 ?></a>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $('#update_foto').click(actualizarFoto);
    $('.btn-light').eq(0).click(actualizarDato);
    $('#btn_log').click(comprobarLog);

    function actualizarFoto(event) {
        let input = document.createElement('input');
        input.setAttribute('type', 'file');
        input.setAttribute('name', 'upd_foto');
        input.setAttribute('class', 'form-control-file mt-4');
        let salto = document.createElement('br');
        let input2 = document.createElement('input');
        input2.setAttribute('type', 'submit');
        input2.setAttribute('value', 'Cambiar');
        input2.setAttribute('class', 'btn btn-primary mt-1 mr-3');
        input2.setAttribute('disabled', 'true');
        input2.setAttribute('id', 'update_foto_sbm');
        let input3 = document.createElement('input');
        input3.setAttribute('type', 'button');
        input3.setAttribute('value', 'Cancelar');
        input3.setAttribute('class', 'btn btn-secondary mt-1');
        input3.setAttribute('id', 'cancel_foto');
        event.target.parentNode.appendChild(input);
        event.target.parentNode.appendChild(salto);
        event.target.parentNode.appendChild(input2);
        event.target.parentNode.appendChild(input3);
        $('[name=upd_foto]').eq(0).change(function() {$('#update_foto_sbm').prop('disabled', false);});
        $('#cancel_foto').click(cancelarFoto);
        $('#update_foto').unbind('click');
    }

    function cancelarFoto(event) {
        let foo = event.target.parentNode;
        foo.removeChild(foo.lastChild);
        foo.removeChild(foo.lastChild);
        foo.removeChild(foo.lastChild);
        foo.removeChild(foo.lastChild);
        $('#update_foto').click(actualizarFoto);
    }

    function actualizarDato(event) {
        event.stopPropagation();
        //event.cancelBubble = true;
        $('.btn-light').eq(0).unbind('click');
        let formulario = document.createElement('form');
        formulario.setAttribute('method', 'post');
        formulario.setAttribute('action', 'perfil.php');
        let input = document.createElement('input');
        input.setAttribute('type', 'text');
        if(event.target.name==="chg_name") {
            input.setAttribute('name', 'upd_name');
        } else {
            input.setAttribute('name', 'upd_dni');
        }
        input.setAttribute('class', 'form-control mt-3');
        let salto = document.createElement('br');
        let subm = document.createElement('input');
        subm.setAttribute('type', 'submit');
        subm.setAttribute('value', 'Cambiar');
        subm.setAttribute('class', 'btn btn-primary mr-3');
        let cancel = document.createElement('input');
        cancel.setAttribute('type', 'button');
        cancel.setAttribute('value', 'Cancelar');
        cancel.setAttribute('class', 'btn btn-secondary');
        cancel.setAttribute('id', 'cancel_update');
        formulario.appendChild(input);
        formulario.appendChild(salto);
        formulario.appendChild(subm);
        formulario.appendChild(cancel);
        event.target.parentNode.appendChild(formulario);
        $('#cancel_update').click(cancelar);
    }

    function cancelar(event) {
        event.target.parentNode.parentNode.removeChild(event.target.parentNode);
        $('.btn-light').eq(0).click(actualizarDato);
    }

    function comprobarLog() {
        alert("Esto aun no funciona!");
    }

    $('.dispositivos_list').on('click', function () {
        $('.dispositivos_list').not(this).popover('hide');
    });

    $('.programas_list').on('click', function () {
        $('.programas_list').not(this).popover('hide');
    });

    $('#prg_tab').on('click', function () {
        $('.dispositivos_list').popover('hide');
        $('.programas_list').popover('hide');
        $('.escenas_list').popover('hide');
    });

    $('#disp_tab').on('click', function () {
        $('.dispositivos_list').popover('hide');
        $('.programas_list').popover('hide');
        $('.escenas_list').popover('hide');
    });

    $('#scn_tab').on('click', function () {
        $('.dispositivos_list').popover('hide');
        $('.programas_list').popover('hide');
        $('.escenas_list').popover('hide');
    });

</script>