<div class="container cambio_pass mt-5 mb-5">
    <form method="post" action="link.php">
        <p><?= $i_recuperar_texto1 ?></p>
        <input type="text" class="form-control" name="email_chg">
        <small class="form-text text-muted"><?= $i_recuperar_texto2 ?></small>
        <input type="submit" name="submit" class="btn btn-primary mt-3" value="<?= $i_recuperar_boton1 ?>">
    </form>
</div>
