<div class="container mt-5 mb-5">
    <div class="row">
        <div class="col-6 offset-3">
            <?php if (isset($_GET['error'])) : ?>
                <p id="texto_error">ERROR! El email introducido no existe!</p>
            <?php endif; ?>
            <form method="post" action="recuperar.php">
                <p><?= $i_recuperar_texto1 ?></p>
                <input type="text" class="form-control" name="email_chg">
                <div class="invalid-feedback"><?= $i_guser_error2 ?></div>
                <small class="form-text text-muted"><?= $i_recuperar_texto2 ?></small>
                <input type="button" name="submit_recovery" class="btn btn-primary mt-3"
                       value="<?= $i_recuperar_boton1 ?>">
            </form>
        </div>
    </div>
</div>
<script>
    document.getElementsByName('submit_recovery')[0].onclick = comprobarEmail;
    let regex_email = /^.+@.+\..+$/;

    function comprobarEmail(event) {
        if (document.getElementsByName('email_chg')[0].value === "" || regex_email.test(document.getElementsByName('email_chg')[0].value) === false) {
            document.getElementsByName('email_chg')[0].classList.add('is-invalid');
        } else {
            event.target.parentNode.submit();
        }
    }
</script>
